#include "8Band_Exported/Project_ADAU146xSchematic_0_PARAM.h"

struct CoefADDR{
    int a1;
    int a2;
    int b0;
    int b1;
    int b2;
};

CoefADDR addrArray[8];

void initAddressArray() {
    addrArray[0].b0 = MOD_GENSECONDORDER_7_STAGE0_B0_ADDR;
    addrArray[0].b1 = MOD_GENSECONDORDER_7_STAGE0_B1_ADDR;
    addrArray[0].b2 = MOD_GENSECONDORDER_7_STAGE0_B2_ADDR;
    addrArray[0].a1 = MOD_GENSECONDORDER_7_STAGE0_A1_ADDR;
    addrArray[0].a2 = MOD_GENSECONDORDER_7_STAGE0_A2_ADDR;

    addrArray[1].b0 = MOD_GENSECONDORDER_7_STAGE1_B0_ADDR;
    addrArray[1].b1 = MOD_GENSECONDORDER_7_STAGE1_B1_ADDR;
    addrArray[1].b2 = MOD_GENSECONDORDER_7_STAGE1_B2_ADDR;
    addrArray[1].a1 = MOD_GENSECONDORDER_7_STAGE1_A1_ADDR;
    addrArray[1].a2 = MOD_GENSECONDORDER_7_STAGE1_A2_ADDR;

    addrArray[2].b0 = MOD_GENSECONDORDER_7_STAGE2_B0_ADDR;
    addrArray[2].b1 = MOD_GENSECONDORDER_7_STAGE2_B1_ADDR;
    addrArray[2].b2 = MOD_GENSECONDORDER_7_STAGE2_B2_ADDR;
    addrArray[2].a1 = MOD_GENSECONDORDER_7_STAGE2_A1_ADDR;
    addrArray[2].a2 = MOD_GENSECONDORDER_7_STAGE2_A2_ADDR;

    addrArray[3].b0 = MOD_GENSECONDORDER_7_STAGE3_B0_ADDR;
    addrArray[3].b1 = MOD_GENSECONDORDER_7_STAGE3_B1_ADDR;
    addrArray[3].b2 = MOD_GENSECONDORDER_7_STAGE3_B2_ADDR;
    addrArray[3].a1 = MOD_GENSECONDORDER_7_STAGE3_A1_ADDR;
    addrArray[3].a2 = MOD_GENSECONDORDER_7_STAGE3_A2_ADDR;

    addrArray[4].b0 = MOD_GENSECONDORDER_7_STAGE4_B0_ADDR;
    addrArray[4].b1 = MOD_GENSECONDORDER_7_STAGE4_B1_ADDR;
    addrArray[4].b2 = MOD_GENSECONDORDER_7_STAGE4_B2_ADDR;
    addrArray[4].a1 = MOD_GENSECONDORDER_7_STAGE4_A1_ADDR;
    addrArray[4].a2 = MOD_GENSECONDORDER_7_STAGE4_A2_ADDR;

    addrArray[5].b0 = MOD_GENSECONDORDER_7_STAGE5_B0_ADDR;
    addrArray[5].b1 = MOD_GENSECONDORDER_7_STAGE5_B1_ADDR;
    addrArray[5].b2 = MOD_GENSECONDORDER_7_STAGE5_B2_ADDR;
    addrArray[5].a1 = MOD_GENSECONDORDER_7_STAGE5_A1_ADDR;
    addrArray[5].a2 = MOD_GENSECONDORDER_7_STAGE5_A2_ADDR;

    addrArray[6].b0 = MOD_GENSECONDORDER_7_STAGE6_B0_ADDR;
    addrArray[6].b1 = MOD_GENSECONDORDER_7_STAGE6_B1_ADDR;
    addrArray[6].b2 = MOD_GENSECONDORDER_7_STAGE6_B2_ADDR;
    addrArray[6].a1 = MOD_GENSECONDORDER_7_STAGE6_A1_ADDR;
    addrArray[6].a2 = MOD_GENSECONDORDER_7_STAGE6_A2_ADDR;

    addrArray[7].b0 = MOD_GENSECONDORDER_7_STAGE7_B0_ADDR;
    addrArray[7].b1 = MOD_GENSECONDORDER_7_STAGE7_B1_ADDR;
    addrArray[7].b2 = MOD_GENSECONDORDER_7_STAGE7_B2_ADDR;
    addrArray[7].a1 = MOD_GENSECONDORDER_7_STAGE7_A1_ADDR;
    addrArray[7].a2 = MOD_GENSECONDORDER_7_STAGE7_A2_ADDR;
}
